// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Get a hello greeting, optionally personalized
    #
    # + name - Optional name to personalize the greeting with
    # + return - returns can be any of following types
    # http:Ok (The greeting)
    # http:BadRequest (Invalid request)
    resource function get greeting(string? name) returns Greeting|ErrorBadRequest {
        if name is string {
            if name.trim().length() == 0 {
                return {
                    body: {
                        code: 400,
                        message: "invalid name",
                        description: "The name query parameter must not be blank"
                    }
                };
            }
            return {name, message: string `Hello, ${name}!`};
        }
        return {message: "Hello, World!"};
    }
}

public type Greeting record {
    # The name supplied by the caller, if any
    string? name?;
    # The greeting text, e.g. "Hello, World!"
    string message;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};
